[project]
name = "password-strength-checker"
version = "0.1.0"
description = "A Streamlit application to check password strength"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "streamlit==1.32.0",
    "regex==2023.12.25",
    "python-dotenv==1.0.0"
]
