[project]
name = "personal-library-manager"
version = "0.1.0"
description = "A command-line application to manage your personal book collection"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "colorama>=0.4.6",
    "rich>=13.7.0"
]
