[project]
name = "data-cleaner"
version = "0.1.0"
description = "A data cleaning and conversion tool"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "streamlit>=1.32.0",
    "pandas>=2.0.0",
    "openpyxl>=3.1.0"
]
